# Generated by Django 5.2.6 on 2025-09-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_disliked_by_quote_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='liked_by',
        ),
    ]
