# Generated by Django 5.2.6 on 2025-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_disliked_by_remove_quote_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_votes',
            field=models.JSONField(default=dict),
        ),
    ]
