# Generated by Django 5.2.6 on 2025-09-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_user_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user_votes',
        ),
    ]
